apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-k8s-app-rollouts
  newName: yemiwebby/aks-k8s-app-rollouts
  newTag: 60b3a6d695d538c0b08940144cbe70d303e71be9
- name: aks-k8s-rollouts
  newName: aks-k8s-rollouts
  newTag: v1
