apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-k8s-app-rollouts
  newName: yemiwebby/aks-k8s-app-rollouts
  newTag: 0d051a1544bc22b09a1cd87d5f1431afbb52bf06
- name: aks-k8s-rollouts
  newName: aks-k8s-rollouts
  newTag: v1
