apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-k8s-app-rollouts
  newName: yemiwebby/aks-k8s-app-rollouts
  newTag: 94c16803ca85110bf2612044ff52ae9554ea330c
- name: aks-k8s-rollouts
  newName: aks-k8s-rollouts
  newTag: v1
